import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Lao } from "next/font/google";
import "./globals.css";
import "./index.css";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifLao = Noto_Serif_Lao({
  subsets: ["lao"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Laoswords Admin",
  description: "Generated by Vanlakhan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerifLao.className} `}>
        {children}
        <Toaster /> {/* ← This renders all toasts globally */}
      </body>
    </html>
  );
}
